name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if you are using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3  # Updated to version 3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4  # Updated to version 4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Adjust if your files are in a different folder
